### ISSUE TITLE
notebook issue tracker

### ISSUE THREAD

**Issue by thuvasooriya** [mora-bprs/SAM-model#6]
- [x] detecting null masks and scanning the image for possible successful masks @thuvasooriya 
- [x] explore area selection masks @thuvasooriya 
- [x] fix sam inference @thuvasooriya @SasikaA073 
- [x] implement sam and fastsam metrics @thuvasooriya 
- [x] clean up the notebook and finalize @thuvasooriya @SasikaA073 
- [x] add license info of models used and datasets used @SasikaA073 
- [x] add proper references of models weights datasets and repos @SasikaA073 
- [x] finding official links to weights and datasets or self hosting them in hugging face for reproducibility @SasikaA073
- [x] testing the notebook works properly on windows @SasikaA073 
- [x] integrating scores into the plot function @thuvasooriya 
- [x] move python scripts to separate directory to generalize them @thuvasooriya
